### ISSUE TITLE
Request for addition

### ISSUE THREAD

**Issue by Bread-sauce** [Opaque02/QBitHelper#1]
Can you add a way to make the bot post status once every 30mins?

**Comment by Opaque02** [comment]
Hi! 

So I just want to start this off by saying I'm not a programmer and this is all 100% a project of love, and this was only tested VERY briefly so it may not work 100%, but if you want to have it auto run instead of being manually updated, here's what I got. Also, this only does currently downloading stuff, not completed (though if you want to change it you can.

First thing at the top of the file you'll see a few lines that say "import...." - I want you to add one extra line beneath it for "import time". This will mean your code at the very top will look like this:

```
import discord
from discord.ext import commands
import requests
import time
```

Next at the very bottom, you'll see on line 237 of the current version (probably 238 once you add the import time line) this bit of code: 

```
async def status(ctx, *args):
```

Delete everything from that point to the very end of the document. The last command should now be this (keep that as the last command): 

```
@bot.command(
        help = "Use this to see the status of what's currently downloading."+"\n"+"If you want to get fancy, you can search for movies/tv shows specifically by type $status movies or $status tv."+"\n"+"You can also see what's completed by doing $status completed, or $status all to see everything."+"\n"+"Finally, you can combine these (like $status tv completed) to only see completed tv shows."+"\n"+"(tip: you can see everything by typing $status all)",
        brief = "Use this to see what's currently downloading"
    )
```

After that command is done, paste in this code at the very very bottom of the file:

```
async def autorun(ctx, *args):
    channelID=ctx.message.channel.id
    if botChannel==channelID:
        while True:
            def not_pinned(message):
                return not message.pinned
            await ctx.message.channel.purge(check=not_pinned)
            updateStatus=DownloadingStatus
            Category="all"
            DiscordList=updateAll(Category,updateStatus)
            if DiscordList!=NothingDownloading:
                for i in range(len(DiscordList)):
                        await ctx.channel.send(DiscordList[i])
            else:
                await ctx.channel.send(NothingDownloading)
            time.sleep(10)
        
bot.run(TOKEN)
```

That's it! Now if you want to change how often it updates you can change the 1800 line (though I'm not sure how often bots can delete/update/send messages on discord without being throttled, so you may have to keep an eye out if it's too often)

**To run it:** instead of typing $status, now type $autorun

This will then delete all the messages in your current channel and update this every 30 minutes with the new information.

**ONE NOTE:** I haven't made a way to officially stop it, so if you want to, you'll have to stop the program manually. Just watch out as if it's in the middle of its 'sleep' cycle, you may have to potentially wait for it to finish its cycle before it closes, which could potentially mean waiting 30 minutes for it to close.

Hope this works! Let me know if it does and how it goes!

Good luck!

**Comment by Bread-sauce** [comment]
Sweet thank you!

**Comment by Bread-sauce** [comment]
Bad news, it doesn't run the purge command correctly and it just builds up.

**Comment by Opaque02** [comment]
> 
> 
> Bad news, it doesn't run the purge command correctly and it just builds up.

Whoops, made a mistake on the repeat part of it. 

In that last section, instead of what I had before, put this in instead (I'm also going to edit my earlier comment so others won't have the same issue):

```
async def autorun(ctx, *args):
    channelID=ctx.message.channel.id
    if botChannel==channelID:
        while True:
            def not_pinned(message):
                return not message.pinned
            await ctx.message.channel.purge(check=not_pinned)
            updateStatus=DownloadingStatus
            Category="all"
            DiscordList=updateAll(Category,updateStatus)
            if DiscordList!=NothingDownloading:
                for i in range(len(DiscordList)):
                        await ctx.channel.send(DiscordList[i])
            else:
                await ctx.channel.send(NothingDownloading)
            time.sleep(10)
        
bot.run(TOKEN)
```

That should do the trick!

**Comment by Bread-sauce** [comment]
Works great now thank you!

**Comment by Opaque02** [comment]
No worries! Closing this off now, but enjoy!
